### ISSUE TITLE
Heartbeat - Backup takes floating ip sometime after giving it away even though primary should be up

### ISSUE THREAD

**Issue by nimertz** [DevOps2021-gb/devops2021#171]

**Comment by nimertz** [comment]
java.lang.IllegalStateException: Session node0pg025ojqkwt21kqv1fw2wywua86417 already in cache
	at org.eclipse.jetty.server.session.AbstractSessionCache.add(AbstractSessionCache.java:467)
	at org.eclipse.jetty.server.session.SessionHandler.newHttpSession(SessionHandler.java:769)
	at org.eclipse.jetty.server.Request.getSession(Request.java:1607)
	at org.eclipse.jetty.server.Request.getSession(Request.java:1581)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:279)
	at spark.Request.session(Request.java:446)
	at spark.http.matching.RequestWrapper.session(RequestWrapper.java:223)
	at utilities.Requests.getAttribute(Requests.java:26)
	at utilities.Requests.getSessionUserId(Requests.java:38)
	at controllers.Endpoints.timeline(Endpoints.java:104)
	at services.MaintenanceService.benchMarkEndpoint(MaintenanceService.java:105)
	at controllers.Endpoints.lambda$registerEndpoints$9(Endpoints.java:67)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

Apr 25, 2021 4:29:04 PM services.LogService logErrorWithMessage

WARNING: EndpointsEndpoint error /  :  null

**Comment by nimertz** [comment]
We have increased the time in between checking if the primary is up to try and avoid session errors
